dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - development

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.3
      env: WP_VERSION=nightly CODE_STYLES=phpcs
    - php: 7.3
      env: WP_VERSION=5.1 CODE_STYLES=phpcs
    - php: 7.2
      env: WP_VERSION=nightly
    - php: 7.2
      env: WP_VERSION=5.0 CODE_STYLES=phpcs
    - php: 7.2
      env: WP_VERSION=4.9 CODE_STYLES=phpcs
    - php: 7.2
      env: WP_VERSION=4.8 CODE_STYLES=phpcs
    - php: 7.2
      env: WP_VERSION=4.7 CODE_STYLES=phpcs
    - php: 7.1
      env: WP_VERSION=nightly
    - php: 7.0
      env: WP_VERSION=nightly
    - php: 5.6
      env: WP_VERSION=5.1
    - php: 5.6
      env: WP_VERSION=5.0
    - php: 5.6
      env: WP_VERSION=4.9
    - php: 5.6
      env: WP_VERSION=4.8
    - php: 5.6
      env: WP_VERSION=4.7
    - php: 5.6
      env: WP_VERSION=nightly

before_script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash _test/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi
  - |
    if [[ "$CODE_STYLES" == "phpcs" ]] ; then
      composer install
      ./vendor/bin/phpcs --version
      ./vendor/bin/phpcs -i
      ./vendor/bin/phpcs --standard=WordPress --report=summary ./index.php ./utm-dot-codes.php ./classes
      ./vendor/bin/phpcs --standard=PHPCompatibility -p --runtime-set testVersion  5.6- --report=summary ./index.php ./utm-dot-codes.php ./classes
    fi

script:
  - cd _test
  - mkdir -p build/logs
  - |
    if [[ "$CODE_STYLES" == "phpcs" ]] ; then
      ../vendor/bin/phpunit
      WP_MULTISITE=1 ../vendor/bin/phpunit
    else
      phpunit
      WP_MULTISITE=1 phpunit
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
